## **Phase 2 (Peer Review)**

#### Project Information

**Research Question:** How can regional and weather factors like cloud cover and elevation influence the performance of drivers across teams, possibly highlighting team-specific specializations?

**Dataset Description (F1 Race Data)**
> https://openf1.org/docs/

<sup><sub>**Notes about the dataset:** The first dataset includes historical F1 race data able to be filtered by driver, race, or date. We can compare different teams and individuals and how their lap times, their pit duration, and any other relevant podium-seeking information varies. Via the OpenF1 API (https://github.com/br-g/openf1), we get access to car telemetry (https://openf1.org/docs/#car-data), lap times (https://openf1.org/docs/#laps), race positions (https://openf1.org/docs/#position), pit stops (https://openf1.org/docs/#pit), and race control (https://openf1.org/docs/#race-control) from all races, teams, and racers. Access is limited to historical data, meaning the 2023 season onward. The weather information (https://openf1.org/docs/#weather) is quite limited excluding factors like cloud cover and elevation, which is why we are looking at Open Meteo API to supplement OpenF1. On OpenF1, there are also generous rate limits of 3 requests per second or 30 requests per minute (https://openf1.org/#faq). OpenF1 is a free, community-run API, so its data is generally reliable for stats because it's a large community, but it isn't an official source of record. Veritably, OpenF1 is directly based on F1 timing/telemetry data making it suitable for academic-style preparatory work, which is our purpose.</sub></sup>

**Dataset Description (Weather Data)**
> https://open-meteo.com/en/docs/historical-weather-api

<sup><sub>**Notes about the dataset:** The second dataset includes realtime, historical weather data that can be used to supplement our analysis of race results. The main access limitation with the Open Meteo API is the spatial resolution, having grid cells ranging from 11 km to 25 km in size. The specific set we’d end up using is likely the ERA5 (https://doi.org/10.24381/cds.adbb2d47) for our use case. These reports are hourly and constructed from data 1950 and onward. Open Meteo, construction described at this site (https://doi.org/10.5281/ZENODO.7970649) may lose some reliability in how its data is built off of reanalysis of various sources (weather stations, aircrafts, buoys, radar, etc.) rather than a point observation.</sub></sup>

#### Data cleaning

##### Libraries

In [39]:
# installing necessary libraries
%pip install seaborn pandas duckdb requests numpy

Requirement already satisfied: seaborn in /usr/local/python/3.14.2/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: duckdb in /usr/local/python/3.14.2/lib/python3.14/site-packages (1.5.6)
Requirement already satisfied: requests in /home/codespace/.local/lib/python3.14/site-packages (2.34.2)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.4)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from seaborn) (3.11.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.14/site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.14/site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /home/codespace/.local/lib/python3.14/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/codespace/.local/lib/python3.14/site-packages (from requests) (2026.7.22)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [40]:
# loading necessary libraries and packages to handle our data
import requests # to extract from datasets
import pandas as pd # to handle the dataframes
import duckdb # to clean the data
from datetime import datetime # to handle the date time format

Note for above code chunk(s), will be modifying and editing as we go to ensure we have what we need to handle our data.

##### Race Session Import and Cleansing

In [41]:
# code OpenF1 API informs us to use to import
from urllib.request import urlopen
import json
response = urlopen('https://api.openf1.org/v1/sessions')
data = json.loads(response.read().decode('utf-8'))
temp_races_df = pd.DataFrame(data) # last line of provided code from API

For above code, this was provided by OpenF1 API in (https://openf1.org/docs) for information on how to import/scrape.

In [48]:
temp_races_df # checking the column headers
temp_races_df['session_type'].unique() # checking to see what the different types are to make sure we don't truncate

# selecting the wanted columns and races
races_df = duckdb.sql("SELECT session_key, session_type, session_name, date_start, date_end, circuit_short_name, country_name, location, year \
                      FROM temp_races_df WHERE ((session_type = 'Race' OR session_type = 'Qualifying') AND is_cancelled = False) \
                      AND year < 2026").df()
races_df # checking the product and modifying sql as necessary to prune canceled races and races from 2026 (ongoing) season
races_df['date_start'] = pd.to_datetime(races_df['date_start'], format='mixed') # reformat dates
races_df['date_end'] = pd.to_datetime(races_df['date_end'], format='mixed')
# wanting to uniform the time zone and make it more easily comprehensible for human reading
races_df['date_start'] = races_df['date_start'].dt.tz_convert("EST").dt.tz_localize(None)
races_df['date_end'] = races_df['date_end'].dt.tz_convert("EST").dt.tz_localize(None)
races_df # checking date time

,session_key,session_type,session_name,date_start,date_end,circuit_short_name,country_name,location,year
0,7768,Qualifying,Qualifying,2023-03-04 10:00:00,2023-03-04 11:00:00,Sakhir,Bahrain,Sakhir,2023
1,7953,Race,Race,2023-03-05 10:00:00,2023-03-05 12:00:00,Sakhir,Bahrain,Sakhir,2023
2,7775,Qualifying,Qualifying,2023-03-18 12:00:00,2023-03-18 13:00:00,Jeddah,Saudi Arabia,Jeddah,2023
3,7779,Race,Race,2023-03-19 12:00:00,2023-03-19 14:00:00,Jeddah,Saudi Arabia,Jeddah,2023
4,7783,Qualifying,Qualifying,2023-04-01 01:00:00,2023-04-01 02:00:00,Melbourne,Australia,Melbourne,2023
...,...,...,...,...,...,...,...,...,...
171,9845,Race,Sprint,2025-11-29 09:00:00,2025-11-29 10:00:00,Lusail,Qatar,Lusail,2025
172,9846,Qualifying,Qualifying,2025-11-29 13:00:00,2025-11-29 14:00:00,Lusail,Qatar,Lusail,2025
173,9850,Race,Race,2025-11-30 11:00:00,2025-11-30 13:00:00,Lusail,Qatar,Lusail,2025
174,9835,Qualifying,Qualifying,2025-12-06 09:00:00,2025-12-06 10:00:00,Yas Marina Circuit,United Arab Emirates,Yas Island,2025
175,9839,Race,Race,2025-12-07 08:00:00,2025-12-07 10:00:00,Yas Marina Circuit,United Arab Emirates,Yas Island,2025

Here, we have cleaned a DataFrame to contain the dates and times for races and the races that qualify the teams to participate in the larger race for narrowing down the time and date for the weather conditions. We also made sure to maintain the specific names of the locations to further assist us when looping in information from Open Meteo. We found the session types listed were `[Practice, Qualifying, Race]` and chose to disregard Practices since teams use these for practice and performance may not be up to par; in other words, since the teams are warming up or practicing on the track, the information consumed may not be as relevant to driver overall performance when representing their team name. One other important thing to note is that we filtered out the race dates from 2026. Since the 2026 F1 season is still ongoing, these races will lack information about the performance of teams and their drivers. We prefer to handle a constantly changing dataset, so we decided to stick with 2023, 2024, and 2025 where all the data is set.

##### Drivers and Their Teams Import and Cleansing

In [44]:
# code OpenF1 API informs us to use to import
response = urlopen('https://api.openf1.org/v1/drivers')
data = json.loads(response.read().decode('utf-8'))
temp_drivers_df = pd.DataFrame(data) # last line of provided code from API

For above code, this was provided by OpenF1 API in (https://openf1.org/docs) for information on how to import/scrape.

In [60]:
temp_drivers_df # checking the column headers
temp_drivers_df['broadcast_name'].unique() # seeing who is really driver because original is 10k lines

drivers_df = duckdb.sql("SELECT DISTINCT r.year, d.driver_number, d.full_name, d.name_acronym, d.team_name, d.country_code \
                      FROM temp_drivers_df d JOIN races_df r ON r.session_key = d.session_key ORDER BY d.full_name, d.team_name, r.year").df()
drivers_df

,year,driver_number,full_name,name_acronym,team_name,country_code
0,2023,23,Alexander ALBON,ALB,Williams,THA
1,2024,23,Alexander ALBON,ALB,Williams,THA
2,2025,23,Alexander ALBON,ALB,Williams,NaN
3,2023,55,Carlos SAINZ,SAI,Ferrari,ESP
4,2024,55,Carlos SAINZ,SAI,Ferrari,ESP
...,...,...,...,...,...,...
65,2024,22,Yuki TSUNODA,TSU,RB,JPN
66,2025,22,Yuki TSUNODA,TSU,Racing Bulls,NaN
67,2025,22,Yuki TSUNODA,TSU,Red Bull Racing,NaN
68,2023,24,ZHOU Guanyu,ZHO,Alfa Romeo,CHN
69,2024,24,ZHOU Guanyu,ZHO,Kick Sauber,CHN

Here, we have cleaned a DataFrame to contain the names, team names, years, and countries of the drivers. One thing that makes this dataset difficult to handle is how the same driver might have different driver numbers or teams or country associations year to year. This is something we will have to deal with as we analyze the data. I decided to join the race date information to help add understanding to the team associations. Since team associations might shift year to year, this helps narrow it down. Additionally, joining on the session keys helps ensure we aren't including information from practices since the session keys from `races_df` would be pruned down by date, race cancellation, etc. We choose to focus on `session_key` and not `meeting_key` since `meeting_key` is specific to special meets and chunks entire weekends together. `session_key` keeps each individual track session separate, which is far more specific.

##### Weather Information Import and Cleansing

In [ ]:
races_df['circuit_short_name'].unique() # to print out the entire full list of circuit names scrollable

# research each circuit name for latitude and longitude
circuit_coords = {
    # OpenF1 circuit_short_name: (latitude, longitude) # full name
    "Sakhir": (26.0325, 50.5106),   # Bahrain International Circuit
    "Jeddah": (21.6319, 39.1044),   # Jeddah Corniche Circuit
    "Melbourne": (-37.8497, 144.9680),   # Albert Park
    "Baku": (40.3725, 49.8533),   # Baku City Circuit
    "Miami": (25.9581, -80.2389),   # Miami International Autodrome
    "Monte Carlo": (43.7347, 7.4206),   # Circuit de Monaco
    "Catalunya": (41.5700, 2.2611),   # Circuit de Barcelona-Catalunya
    "Montreal": (45.5017, -73.5228),   # Circuit Gilles Villeneuve
    "Spielberg": (47.2197, 14.7647),   # Red Bull Ring
    "Silverstone": (52.0786, -1.0169),   # Silverstone Circuit
    "Hungaroring": (47.5789, 19.2486),   # Hungaroring
    "Spa-Francorchamps": (50.4372, 5.9714),   # Circuit de Spa-Francorchamps
    "Zandvoort": (52.3888, 4.5409),   # Circuit Zandvoort
    "Monza": (45.6156, 9.2811),   # Autodromo Nazionale Monza
    "Singapore": (1.2914, 103.8640),   # Marina Bay Street Circuit
    "Suzuka": (34.8431, 136.5410),   # Suzuka International Racing Course
    "Lusail": (25.4900, 51.4542),   # Lusail International Circuit
    "Austin": (30.1328, -97.6411),   # Circuit of the Americas
    "Mexico City": (19.4042, -99.0907),   # Autódromo Hermanos Rodríguez
    "Interlagos": (-23.7036, -46.6997),   # Autódromo José Carlos Pace
    "Las Vegas": (36.1147, -115.1728),   # Las Vegas Strip Circuit
    "Yas Marina Circuit": (24.4672, 54.6031),   # Yas Marina Circuit
    "Shanghai": (31.3389, 121.2197),   # Shanghai International Circuit
    "Imola": (44.3439, 11.7167),   # Autodromo Enzo e Dino Ferrari
}

coords_df = pd.DataFrame.from_dict(circuit_coords, orient='index', columns=['latitude', 'longitude']).rename_axis("circuit_short_name").reset_index()
coords_df # ensure it looks correct

# prepping to input information to Open Meteo in their specified format
# latitude, longitude, , timezone, start date, end date
temp_races_df['date_start'] = races_df['date_start'].dt.strftime("%Y-%m-%d")
temp_races_df['date_end'] = races_df['date_end'].dt.strftime("%Y-%m-%d")
openmeteo_input_df = duckdb.sql("SELECT c.latitude, c.longitude, r.date_start, r.date_end FROM coords_df c JOIN temp_races_df r \
                                ON c.circuit_short_name = r.circuit_short_name WHERE r.date_start != 'NaN' AND r.date_end != 'NaN'").df()
timezone_filler = [',EST'] * 176
openmeteo_input_df.insert(loc=2, column='timezone', value=timezone_filler)
openmeteo_input_df # print to see if format good

openmeteo_input_df.to_csv('openmeteo_input.csv', index=False) # exporting the format
openmeteo_input_df['hour'] = races_df['date_start'].dr.strftime("")

Above, we modified our existing datasets and information to be able to input it to Open Meteo more easily.

In [ ]:
# code provided to us to input for importing data by the Open Meteo website
%pip install openmeteo-requests
%pip install requests-cache retry-requests numpy pandas

import openmeteo_requests
import requests_cache
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

In [ ]:
# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
	"latitude": 26.0325,
	"longitude": 50.5106,
	"start_date": "2023-03-04 00:00:00",
	"end_date": "2023-03-04 01:00:00",
	"hourly": ["temperature_2m", "precipitation", "cloud_cover_low", "cloud_cover_high", "cloud_cover_mid", "cloud_cover", "surface_pressure", "wind_speed_10m", "wind_direction_10m", "wind_gusts_10m", "wind_direction_100m", "wind_speed_100m"],
	"timezone": "EST",
}
responses = openmeteo.weather_api(url, params = params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation: {response.Elevation()} m asl")
print(f"Timezone: {response.Timezone()}{response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
hourly_precipitation = hourly.Variables(1).ValuesAsNumpy()
hourly_cloud_cover_low = hourly.Variables(2).ValuesAsNumpy()
hourly_cloud_cover_high = hourly.Variables(3).ValuesAsNumpy()
hourly_cloud_cover_mid = hourly.Variables(4).ValuesAsNumpy()
hourly_cloud_cover = hourly.Variables(5).ValuesAsNumpy()
hourly_surface_pressure = hourly.Variables(6).ValuesAsNumpy()
hourly_wind_speed_10m = hourly.Variables(7).ValuesAsNumpy()
hourly_wind_direction_10m = hourly.Variables(8).ValuesAsNumpy()
hourly_wind_gusts_10m = hourly.Variables(9).ValuesAsNumpy()
hourly_wind_direction_100m = hourly.Variables(10).ValuesAsNumpy()
hourly_wind_speed_100m = hourly.Variables(11).ValuesAsNumpy()

hourly_data = {
	"date": pd.date_range(
		start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
		end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
		freq = pd.Timedelta(seconds = hourly.Interval()),
		inclusive = "left"
	).tz_convert(response.Timezone().decode())
}

hourly_data["temperature_2m"] = hourly_temperature_2m
hourly_data["precipitation"] = hourly_precipitation
hourly_data["cloud_cover_low"] = hourly_cloud_cover_low
hourly_data["cloud_cover_high"] = hourly_cloud_cover_high
hourly_data["cloud_cover_mid"] = hourly_cloud_cover_mid
hourly_data["cloud_cover"] = hourly_cloud_cover
hourly_data["surface_pressure"] = hourly_surface_pressure
hourly_data["wind_speed_10m"] = hourly_wind_speed_10m
hourly_data["wind_direction_10m"] = hourly_wind_direction_10m
hourly_data["wind_gusts_10m"] = hourly_wind_gusts_10m
hourly_data["wind_direction_100m"] = hourly_wind_direction_100m
hourly_data["wind_speed_100m"] = hourly_wind_speed_100m

hourly_dataframe = pd.DataFrame(data = hourly_data)
print("\nHourly data\n

Coordinates: 26.045692443847656°N 50.514225006103516°E
Elevation: 8.0 m asl
Timezone: b'EST'b'GMT-5'
Timezone difference to GMT+0: -18000s

Hourly data
                         date  temperature_2m  precipitation  cloud_cover_low  \
0  2023-03-04 00:00:00-05:00       18.650000            0.0              0.0
1  2023-03-04 01:00:00-05:00       22.950001            0.0              0.0
2  2023-03-04 02:00:00-05:00       25.500000            0.0              0.0
3  2023-03-04 03:00:00-05:00       27.250000            0.0              0.0
4  2023-03-04 04:00:00-05:00       28.799999            0.0              0.0
5  2023-03-04 05:00:00-05:00       29.500000            0.0              0.0
6  2023-03-04 06:00:00-05:00       29.850000            0.0              0.0
7  2023-03-04 07:00:00-05:00       29.299999            0.0              0.0
8  2023-03-04 08:00:00-05:00       27.700001            0.0              0.0
9  2023-03-04 09:00:00-05:00       25.350000            0.0              0.0
10 2023-03-04 10:00:00-05:00       23.250000            0.0              0.0
11 2023-03-04 11:00:00-05:00       22.799999            0.0              0.0
12 2023-03-04 12:00:00-05:00       22.500000            0.0              0.0
13 2023-03-04 13:00:00-05:00       22.250000            0.0              0.0
14 2023-03-04 14:00:00-05:00       21.900000            0.0              0.0
15 2023-03-04 15:00:00-05:00       21.299999            0.0              0.0
16 2023-03-04 16:00:00-05:00       20.950001            0.0              0.0
17 2023-03-04 17:00:00-05:00       20.400000            0.0              0.0
18 2023-03-04 18:00:00-05:00       19.700001            0.0              0.0
19 2023-03-04 19:00:00-05:00       19.100000            0.0              0.0
20 2023-03-04 20:00:00-05:00       18.250000            0.0              0.0
21 2023-03-04 21:00:00-05:00       17.799999            0.0              0.0
22 2023-03-04 22:00:00-05:00       17.350000            0.0              0.0
23 2023-03-04 23:00:00-05:00       19.150000            0.0              0.0

    cloud_cover_high  cloud_cover_mid  cloud_cover  surface_pressure  \
0                0.0              0.0          0.0       1020.543884
1                0.0              0.0          0.0       1020.957275
2                0.0              0.0          0.0       1020.665527
3                0.0              0.0          0.0       1020.271301
4                0.0              0.0          0.0       1019.077209
5                0.0              0.0          0.0       1018.180176
6                0.0              0.0          0.0       1017.481812
7                0.0              0.0          0.0       1017.080566
8                0.0              0.0          0.0       1016.976013
9                0.0              0.0          0.0       1017.268311
10               0.0              0.0          0.0       1017.361511
11               0.0              0.0          0.0       1017.659912
12               0.0              0.0          0.0       1018.358276
13               0.0              0.0          0.0       1018.457397
14               0.0              0.0          0.0       1018.256592
15               0.0              0.0          0.0       1018.054810
16               0.0              0.0          0.0       1017.953613
17               0.0              0.0          0.0       1017.652283
18               0.0              0.0          0.0       1017.250122
19               0.0              0.0          0.0       1017.447998
20               0.0              0.0          0.0       1017.545349
21               0.0              0.0          0.0       1018.043335
22               0.0              0.0          0.0       1018.741089
23               0.0              2.0          2.0       1019.546387

    wind_speed_10m  wind_direction_10m  wind_gusts_10m  wind_direction_100m  \
0         1.297998          146.309906        7.200000           135.000107
1         0.509117          315.000092        6.840000           360.000000
2         2.968636          284.036255       11.520000           296.564972
3         4.680000          292.619904       14.759999           306.869965
4         4.896530          323.972534       15.480000           344.744812
5         4.379589          350.537750       15.480000            10.304792
6         3.826853           41.185837       15.119999            57.528828
7        13.397612           59.300358       16.559999            62.102829
8        16.516901           69.590042       27.000000            71.200027
9        15.463244           77.905258       27.000000            78.055847
10       12.605142           88.363464       24.119999            89.045181
11       11.609651           97.124924       18.719999           101.689346
12       10.188700          122.005348       16.559999           128.157272
13       12.496718          138.503632       16.559999           145.080521
14       14.799459          161.564957       20.160000           163.739716
15       16.657539          173.796646       22.680000           175.914459
16       17.283749          178.806534       24.119999           185.376617
17       15.124284          178.636108       24.119999           188.235535
18       13.363711          175.364624       20.880001           184.969650
19       11.525623          181.789871       18.000000           191.888641
20       10.464798          183.945114       15.480000           195.068542
21       10.464798          183.945114       13.679999           198.799988
22        9.605998          192.994614       13.320000           207.699387
23        8.225035          203.198608       12.240000           218.884506

    wind_speed_100m
0          1.018234
1          0.720000
2          2.414953
3          3.600000
4          4.104631
5          4.024922
6          4.693826
7         13.849477
8         17.873554
9         19.134260
10        21.602999
11        21.322214
12        19.228851
13        23.269482
14        26.999998
15        30.317043
16        30.735231
17        27.645092
18        24.933735
19        20.969805
20        19.386591
21        17.873554
22        16.263872
23        14.336861

Coordinates: 26.045692443847656°N 50.514225006103516°E
Elevation: 8.0 m asl
Timezone: b'EST'b'GMT-5'
Timezone difference to GMT+0: -18000s

Hourly data
                         date  temperature_2m  precipitation  cloud_cover_low  \
0  2023-03-05 00:00:00-05:00       22.150000            0.0              0.0
1  2023-03-05 01:00:00-05:00       24.799999            0.0              0.0
2  2023-03-05 02:00:00-05:00       27.200001            0.0              0.0
3  2023-03-05 03:00:00-05:00       28.850000            0.0              0.0
4  2023-03-05 04:00:00-05:00       30.250000            0.0              0.0
5  2023-03-05 05:00:00-05:00       31.400000            0.0              0.0
6  2023-03-05 06:00:00-05:00       32.150002            0.0              0.0
7  2023-03-05 07:00:00-05:00       32.150002            0.0              0.0
8  2023-03-05 08:00:00-05:00       32.000000            0.0              0.0
9  2023-03-05 09:00:00-05:00       30.600000            0.0              0.0
10 2023-03-05 10:00:00-05:00       27.850000            0.0              0.0
11 2023-03-05 11:00:00-05:00       26.299999            0.0              0.0
12 2023-03-05 12:00:00-05:00       25.100000            0.0              0.0
13 2023-03-05 13:00:00-05:00       24.299999            0.0              0.0
14 2023-03-05 14:00:00-05:00       23.549999            0.0              0.0
15 2023-03-05 15:00:00-05:00       21.900000            0.0              0.0
16 2023-03-05 16:00:00-05:00       20.600000            0.0              0.0
17 2023-03-05 17:00:00-05:00       20.100000            0.0              0.0
18 2023-03-05 18:00:00-05:00       19.600000            0.0              0.0
19 2023-03-05 19:00:00-05:00       20.049999            0.0              0.0
20 2023-03-05 20:00:00-05:00       19.350000            0.0              0.0
21 2023-03-05 21:00:00-05:00       19.400000            0.0              0.0
22 2023-03-05 22:00:00-05:00       18.450001            0.0              0.0
23 2023-03-05 23:00:00-05:00       20.100000            0.0              0.0

    cloud_cover_high  cloud_cover_mid  cloud_cover  surface_pressure  \
0                0.0              1.0          1.0       1020.255371
1                0.0              3.0          3.0       1020.763184
2                0.0              0.0          0.0       1020.670898
3                0.0              0.0          0.0       1019.876831
4                0.0              0.0          0.0       1018.781982
5                0.0              0.0          0.0       1017.586548
6                0.0              0.0          0.0       1016.789490
7                0.0              0.0          0.0       1016.489746
8                0.0              0.0          0.0       1016.289551
9                0.0              0.0          0.0       1016.385071
10               0.0              0.0          0.0       1016.676453
11               0.0              0.0          0.0       1017.171265
12               0.0              0.0          0.0       1017.567078
13               0.0              0.0          0.0       1017.464966
14               0.0              0.0          0.0       1017.462463
15               0.0              0.0          0.0       1017.257507
16               0.0              0.0          0.0       1017.153320
17               0.0              0.0          0.0       1016.552368
18               0.0              0.0          0.0       1016.150879
19               0.0              0.0          0.0       1015.652954
20               0.0              0.0          0.0       1015.650635
21               0.0              0.0          0.0       1016.150146
22               0.0              0.0          0.0       1016.447144
23               0.0              0.0          0.0       1017.151794

    wind_speed_10m  wind_direction_10m  wind_gusts_10m  wind_direction_100m  \
0         4.896530          216.027466       10.799999           230.710617
1         2.545584          261.869995       10.440001           262.875092
2         5.351785          289.653900       13.320000           299.054504
3         9.064569          276.842682       19.799999           276.008911
4         8.640000          270.000000       20.519999           270.000000
5         6.034700          252.645889       19.799999           243.435013
6         5.860375          222.510406       16.919998           202.619904
7         8.121970          192.804260       17.280001           174.805664
8        10.105681          175.914459       18.359999           168.310654
9        10.895576          172.405441       18.359999           166.759476
10        9.779817          173.659897       16.199999           173.659897
11       10.105681          175.914459       13.320000           180.000000
12       10.464798          176.054886       14.040000           180.000000
13        9.720000          180.000000       14.040000           184.666779
14       11.159999          180.000000       14.040000           186.842682
15        9.028754          175.426163       14.400000           185.946762
16        7.695920          169.215744       11.520000           184.969650
17        6.297428          210.963684        9.360000           205.942245
18        6.369050          227.290634        8.640000           229.398788
19       10.195057          227.862473        8.280000           226.468735
20       10.483357          254.054535       12.959999           244.855240
21       11.966953          263.088867       15.840000           257.152283
22        9.826088          261.573120       15.480000           258.690094
23        4.553679          288.435028       12.240000           270.000000

    wind_speed_100m
0         10.233123
1          2.902413
2          3.706427
3          6.877790
4          6.120000
5          4.024922
6          4.680000
7          7.952660
8         10.661107
9         12.574260
10        13.039754
11        15.480000
12        17.639999
13        17.698677
14        18.129137
15        17.373497
16        16.622490
17        14.812590
18        13.276144
19        19.862083
20        19.486609
21        21.046917
22        18.356470
23        11.879999

Coordinates: 26.045692443847656°N 50.514225006103516°E
Elevation: 8.0 m asl
Timezone: b'EST'b'GMT-5'
Timezone difference to GMT+0: -18000s

Hourly data
                         date  temperature_2m  precipitation  cloud_cover_low  \
0  2023-03-18 00:00:00-05:00       21.799999            0.0              0.0
1  2023-03-18 01:00:00-05:00       23.200001            0.0              0.0
2  2023-03-18 02:00:00-05:00       24.150000            0.0              0.0
3  2023-03-18 03:00:00-05:00       25.150000            0.0              0.0
4  2023-03-18 04:00:00-05:00       25.700001            0.0              0.0
5  2023-03-18 05:00:00-05:00       26.000000            0.0              0.0
6  2023-03-18 06:00:00-05:00       25.700001            0.0              0.0
7  2023-03-18 07:00:00-05:00       25.299999            0.0              0.0
8  2023-03-18 08:00:00-05:00       24.549999            0.0              0.0
9  2023-03-18 09:00:00-05:00       23.500000            0.0              0.0
10 2023-03-18 10:00:00-05:00       22.049999            0.0              0.0
11 2023-03-18 11:00:00-05:00       21.299999            0.0              0.0
12 2023-03-18 12:00:00-05:00       20.850000            0.0              0.0
13 2023-03-18 13:00:00-05:00       20.200001            0.0              0.0
14 2023-03-18 14:00:00-05:00       19.400000            0.0              0.0
15 2023-03-18 15:00:00-05:00       18.799999            0.0              0.0
16 2023-03-18 16:00:00-05:00       19.150000            0.0              0.0
17 2023-03-18 17:00:00-05:00       18.850000            0.0              0.0
18 2023-03-18 18:00:00-05:00       19.200001            0.0              0.0
19 2023-03-18 19:00:00-05:00       18.400000            0.0              0.0
20 2023-03-18 20:00:00-05:00       17.850000            0.0              0.0
21 2023-03-18 21:00:00-05:00       17.600000            0.0              0.0
22 2023-03-18 22:00:00-05:00       18.150000            0.0              0.0
23 2023-03-18 23:00:00-05:00       19.500000            0.0              0.0

    cloud_cover_high  cloud_cover_mid  cloud_cover  surface_pressure  \
0                0.0              0.0          0.0       1012.861206
1                0.0              0.0          0.0       1013.265320
2                0.0              0.0          0.0       1013.068420
3                0.0              0.0          0.0       1012.671875
4                0.0              0.0          0.0       1011.974121
5                0.0              0.0          0.0       1010.876099
6                0.0              0.0          0.0       1010.375549
7                2.0              0.0         13.0       1010.374268
8                3.0              0.0          3.0       1010.172241
9                1.0              1.0          2.0       1010.368958
10              12.0              0.0         12.0       1010.563965
11              14.0              4.0         17.0       1010.661682
12               8.0              0.0          8.0       1010.660095
13               2.0              0.0          2.0       1010.658203
14               5.0              0.0          5.0       1010.255676
15               1.0              0.0          1.0       1009.854126
16               0.0              0.0          0.0       1009.156067
17               0.0              0.0          0.0       1008.855408
18               0.0              6.0          6.0       1008.157043
19              92.0              7.0          5.0       1007.854797
20              97.0             11.0         97.0       1007.953186
21               0.0             15.0         15.0       1008.451782
22              11.0             25.0         34.0       1009.053101
23               5.0              3.0          5.0       1009.756531

    wind_speed_10m  wind_direction_10m  wind_gusts_10m  wind_direction_100m  \
0        15.137133          334.653870       23.039999           337.380096
1        17.068707          332.354095       28.080000           333.435028
2        19.995398          336.665924       32.760002           337.166290
3        23.688984          343.217285       38.519997           343.300690
4        24.724951          343.939941       40.320000           343.950928
5        25.984917          349.624207       42.119999           349.380402
6        24.609364          354.122711       42.119999           354.068573
7        19.652176          351.573120       39.959999           351.469330
8        18.356470          348.690094       32.039997           348.886993
9        15.986595          352.234924       29.519999           351.085144
10       12.287555          354.957642       24.480000           352.725067
11       11.165805          358.152435       17.280001           354.897919
12       10.464798          356.054901       16.199999           350.706757
13        9.007196          357.709442       14.759999           350.909790
14        7.421590           14.036275       12.240000           357.137665
15        7.172949           17.525669        9.360000           358.492615
16        5.052841            4.085537        9.360000           353.088867
17        4.843305          221.987137        6.480000           302.471161
18        3.396233          237.994659        6.480000           315.000092
19        4.693826          302.471161        7.559999           318.366547
20        7.993298          277.765076        9.720000           286.189270
21        7.289444          290.224945       10.080000           291.447815
22        5.014219          291.037567        9.000000           289.983185
23        1.800000          233.130020        6.480000           262.405457

    wind_speed_100m
0         18.720001
1         19.319628
2         22.264771
3         26.309572
4         27.345785
5         29.301876
6         27.869207
7         21.841648
8         20.545246
9         18.584509
10        17.057314
11        20.240196
12        20.063339
13        18.228943
14        14.417988
15        13.684735
16        11.966953
17         4.693826
18         5.091168
19         8.669949
20        11.620809
21        10.829958
22         8.427383
23         5.447788

Coordinates: 26.045692443847656°N 50.514225006103516°E
Elevation: 8.0 m asl
Timezone: b'EST'b'GMT-5'
Timezone difference to GMT+0: -18000s

Hourly data
                         date  temperature_2m  precipitation  cloud_cover_low  \
0  2023-03-19 00:00:00-05:00       22.650000            0.0              0.0
1  2023-03-19 01:00:00-05:00       25.450001            0.0              0.0
2  2023-03-19 02:00:00-05:00       27.049999            0.0              0.0
3  2023-03-19 03:00:00-05:00       27.900000            0.0              0.0
4  2023-03-19 04:00:00-05:00       28.950001            0.0              0.0
5  2023-03-19 05:00:00-05:00       29.400000            0.0              0.0
6  2023-03-19 06:00:00-05:00       29.799999            0.0              0.0
7  2023-03-19 07:00:00-05:00       31.350000            0.0              0.0
8  2023-03-19 08:00:00-05:00       30.700001            0.0              0.0
9  2023-03-19 09:00:00-05:00       29.500000            0.0              0.0
10 2023-03-19 10:00:00-05:00       26.600000            0.0              0.0
11 2023-03-19 11:00:00-05:00       25.299999            0.0              0.0
12 2023-03-19 12:00:00-05:00       25.000000            0.0              0.0
13 2023-03-19 13:00:00-05:00       24.900000            0.0              0.0

Open Meteo API provided us with specific Python we could use to extract our data. To see the code Open Meteo provided, click [here](https://open-meteo.com/en/docs/historical-weather-api?location_mode=csv_coordinates&csv_coordinates=26.0325,50.5106,,EST,2023-03-04,2023-03-04%0A26.0325,50.5106,,EST,2023-03-05,2023-03-05%0A26.0325,50.5106,,EST,2023-03-18,2023-03-18%0A26.0325,50.5106,,EST,2023-03-19,2023-03-19%0A26.0325,50.5106,,EST,2023-04-01,2023-04-01%0A26.0325,50.5106,,EST,2023-04-02,2023-04-02%0A26.0325,50.5106,,EST,2023-04-28,2023-04-28%0A26.0325,50.5106,,EST,2023-04-29,2023-04-29%0A21.6319,39.1044,,EST,2023-04-29,2023-04-29%0A21.6319,39.1044,,EST,2023-04-30,2023-04-30%0A21.6319,39.1044,,EST,2023-05-06,2023-05-06%0A21.6319,39.1044,,EST,2023-05-07,2023-05-07%0A21.6319,39.1044,,EST,2023-05-27,2023-05-27%0A-37.8497,144.968,,EST,2023-05-28,2023-05-28%0A-37.8497,144.968,,EST,2023-06-03,2023-06-03%0A-37.8497,144.968,,EST,2023-06-04,2023-06-04%0A-37.8497,144.968,,EST,2023-06-17,2023-06-17%0A-37.8497,144.968,,EST,2023-06-18,2023-06-18%0A40.3725,49.8533,,EST,2023-06-30,2023-06-30%0A40.3725,49.8533,,EST,2023-07-01,2023-07-01%0A40.3725,49.8533,,EST,2023-07-01,2023-07-01%0A40.3725,49.8533,,EST,2023-07-02,2023-07-02%0A40.3725,49.8533,,EST,2023-07-08,2023-07-08%0A25.9581,-80.2389,,EST,2023-07-09,2023-07-09%0A25.9581,-80.2389,,EST,2023-07-22,2023-07-22%0A25.9581,-80.2389,,EST,2023-07-23,2023-07-23%0A25.9581,-80.2389,,EST,2023-07-28,2023-07-28%0A25.9581,-80.2389,,EST,2023-07-29,2023-07-29%0A44.3439,11.7167,,EST,2023-07-29,2023-07-29%0A44.3439,11.7167,,EST,2023-07-30,2023-07-30%0A44.3439,11.7167,,EST,2023-08-26,2023-08-26%0A44.3439,11.7167,,EST,2023-08-27,2023-08-27%0A44.3439,11.7167,,EST,2023-09-02,2023-09-02%0A43.7347,7.4206,,EST,2023-09-03,2023-09-03%0A43.7347,7.4206,,EST,2023-09-16,2023-09-16%0A43.7347,7.4206,,EST,2023-09-17,2023-09-17%0A43.7347,7.4206,,EST,2023-09-23,2023-09-23%0A43.7347,7.4206,,EST,2023-09-24,2023-09-24%0A41.57,2.2611,,EST,2023-10-06,2023-10-06%0A41.57,2.2611,,EST,2023-10-07,2023-10-07%0A41.57,2.2611,,EST,2023-10-07,2023-10-07%0A41.57,2.2611,,EST,2023-10-08,2023-10-08%0A41.57,2.2611,,EST,2023-10-20,2023-10-20%0A45.5017,-73.5228,,EST,2023-10-21,2023-10-21%0A45.5017,-73.5228,,EST,2023-10-21,2023-10-21%0A45.5017,-73.5228,,EST,2023-10-22,2023-10-22%0A45.5017,-73.5228,,EST,2023-10-28,2023-10-28%0A45.5017,-73.5228,,EST,2023-10-29,2023-10-29%0A47.2197,14.7647,,EST,2023-11-03,2023-11-03%0A47.2197,14.7647,,EST,2023-11-04,2023-11-04%0A47.2197,14.7647,,EST,2023-11-04,2023-11-04%0A47.2197,14.7647,,EST,2023-11-05,2023-11-05%0A47.2197,14.7647,,EST,2023-11-18,2023-11-18%0A52.0786,-1.0169,,EST,2023-11-19,2023-11-19%0A52.0786,-1.0169,,EST,2023-11-25,2023-11-25%0A52.0786,-1.0169,,EST,2023-11-26,2023-11-26%0A52.0786,-1.0169,,EST,2024-03-01,2024-03-01%0A52.0786,-1.0169,,EST,2024-03-02,2024-03-02%0A47.5789,19.2486,,EST,2024-03-08,2024-03-08%0A47.5789,19.2486,,EST,2024-03-09,2024-03-09%0A47.5789,19.2486,,EST,2024-03-23,2024-03-23%0A47.5789,19.2486,,EST,2024-03-23,2024-03-24%0A47.5789,19.2486,,EST,2024-04-06,2024-04-06%0A50.4372,5.9714,,EST,2024-04-07,2024-04-07%0A50.4372,5.9714,,EST,2024-04-19,2024-04-19%0A50.4372,5.9714,,EST,2024-04-19,2024-04-19%0A50.4372,5.9714,,EST,2024-04-20,2024-04-20%0A50.4372,5.9714,,EST,2024-04-21,2024-04-21%0A52.3888,4.5409,,EST,2024-05-03,2024-05-03%0A52.3888,4.5409,,EST,2024-05-04,2024-05-04%0A52.3888,4.5409,,EST,2024-05-04,2024-05-04%0A52.3888,4.5409,,EST,2024-05-05,2024-05-05%0A52.3888,4.5409,,EST,2024-05-18,2024-05-18%0A45.6156,9.2811,,EST,2024-05-19,2024-05-19%0A45.6156,9.2811,,EST,2024-05-25,2024-05-25%0A45.6156,9.2811,,EST,2024-05-26,2024-05-26%0A45.6156,9.2811,,EST,2024-06-08,2024-06-08%0A45.6156,9.2811,,EST,2024-06-09,2024-06-09%0A1.2914,103.864,,EST,2024-06-22,2024-06-22%0A1.2914,103.864,,EST,2024-06-23,2024-06-23%0A1.2914,103.864,,EST,2024-06-28,2024-06-28%0A1.2914,103.864,,EST,2024-06-29,2024-06-29%0A1.2914,103.864,,EST,2024-06-29,2024-06-29%0A34.8431,136.541,,EST,2024-06-30,2024-06-30%0A34.8431,136.541,,EST,2024-07-06,2024-07-06%0A34.8431,136.541,,EST,2024-07-07,2024-07-07%0A34.8431,136.541,,EST,2024-07-20,2024-07-20%0A34.8431,136.541,,EST,2024-07-21,2024-07-21%0A25.49,51.4542,,EST,2024-07-27,2024-07-27%0A25.49,51.4542,,EST,2024-07-28,2024-07-28%0A25.49,51.4542,,EST,2024-08-24,2024-08-24%0A25.49,51.4542,,EST,2024-08-25,2024-08-25%0A25.49,51.4542,,EST,2024-08-31,2024-08-31%0A30.1328,-97.6411,,EST,2024-09-01,2024-09-01%0A30.1328,-97.6411,,EST,2024-09-14,2024-09-14%0A30.1328,-97.6411,,EST,2024-09-15,2024-09-15%0A30.1328,-97.6411,,EST,2024-09-21,2024-09-21%0A30.1328,-97.6411,,EST,2024-09-22,2024-09-22%0A19.4042,-99.0907,,EST,2024-10-18,2024-10-18%0A19.4042,-99.0907,,EST,2024-10-19,2024-10-19%0A19.4042,-99.0907,,EST,2024-10-19,2024-10-19%0A19.4042,-99.0907,,EST,2024-10-20,2024-10-20%0A19.4042,-99.0907,,EST,2024-10-26,2024-10-26%0A-23.7036,-46.6997,,EST,2024-10-27,2024-10-27%0A-23.7036,-46.6997,,EST,2024-11-01,2024-11-01%0A-23.7036,-46.6997,,EST,2024-11-02,2024-11-02%0A-23.7036,-46.6997,,EST,2024-11-03,2024-11-03%0A-23.7036,-46.6997,,EST,2024-11-03,2024-11-03%0A36.1147,-115.1728,,EST,2024-11-23,2024-11-23%0A36.1147,-115.1728,,EST,2024-11-24,2024-11-24%0A36.1147,-115.1728,,EST,2024-11-29,2024-11-29%0A36.1147,-115.1728,,EST,2024-11-30,2024-11-30%0A36.1147,-115.1728,,EST,2024-11-30,2024-11-30%0A24.4672,54.6031,,EST,2024-12-01,2024-12-01%0A24.4672,54.6031,,EST,2024-12-07,2024-12-07%0A24.4672,54.6031,,EST,2024-12-08,2024-12-08%0A24.4672,54.6031,,EST,2025-03-15,2025-03-15%0A24.4672,54.6031,,EST,2025-03-15,2025-03-16%0A26.0325,50.5106,,EST,2025-03-21,2025-03-21%0A26.0325,50.5106,,EST,2025-03-21,2025-03-21%0A26.0325,50.5106,,EST,2025-03-22,2025-03-22%0A26.0325,50.5106,,EST,2025-03-23,2025-03-23%0A26.0325,50.5106,,EST,2025-04-05,2025-04-05%0A26.0325,50.5106,,EST,2025-04-06,2025-04-06%0A26.0325,50.5106,,EST,2025-04-12,2025-04-12%0A26.0325,50.5106,,EST,2025-04-13,2025-04-13%0A21.6319,39.1044,,EST,2025-04-19,2025-04-19%0A21.6319,39.1044,,EST,2025-04-20,2025-04-20%0A21.6319,39.1044,,EST,2025-05-02,2025-05-02%0A21.6319,39.1044,,EST,2025-05-03,2025-05-03%0A21.6319,39.1044,,EST,2025-05-03,2025-05-03%0A-37.8497,144.968,,EST,2025-05-04,2025-05-04%0A-37.8497,144.968,,EST,2025-05-17,2025-05-17%0A-37.8497,144.968,,EST,2025-05-18,2025-05-18%0A-37.8497,144.968,,EST,2025-05-24,2025-05-24%0A-37.8497,144.968,,EST,2025-05-25,2025-05-25%0A34.8431,136.541,,EST,2025-05-31,2025-05-31%0A34.8431,136.541,,EST,2025-06-01,2025-06-01%0A34.8431,136.541,,EST,2025-06-14,2025-06-14%0A34.8431,136.541,,EST,2025-06-15,2025-06-15%0A34.8431,136.541,,EST,2025-06-28,2025-06-28%0A31.3389,121.2197,,EST,2025-06-29,2025-06-29%0A31.3389,121.2197,,EST,2025-07-05,2025-07-05%0A31.3389,121.2197,,EST,2025-07-06,2025-07-06%0A31.3389,121.2197,,EST,2025-07-25,2025-07-25%0A31.3389,121.2197,,EST,2025-07-26,2025-07-26%0A25.9581,-80.2389,,EST,2025-07-26,2025-07-26%0A25.9581,-80.2389,,EST,2025-07-27,2025-07-27%0A25.9581,-80.2389,,EST,2025-08-02,2025-08-02%0A25.9581,-80.2389,,EST,2025-08-03,2025-08-03%0A25.9581,-80.2389,,EST,2025-08-30,2025-08-30%0A44.3439,11.7167,,EST,2025-08-31,2025-08-31%0A44.3439,11.7167,,EST,2025-09-06,2025-09-06%0A44.3439,11.7167,,EST,2025-09-07,2025-09-07%0A44.3439,11.7167,,EST,2025-09-20,2025-09-20%0A44.3439,11.7167,,EST,2025-09-21,2025-09-21%0A43.7347,7.4206,,EST,2025-10-04,2025-10-04%0A43.7347,7.4206,,EST,2025-10-05,2025-10-05%0A43.7347,7.4206,,EST,2025-10-17,2025-10-17%0A43.7347,7.4206,,EST,2025-10-18,2025-10-18%0A43.7347,7.4206,,EST,2025-10-18,2025-10-18%0A45.5017,-73.5228,,EST,2025-10-19,2025-10-19%0A45.5017,-73.5228,,EST,2025-10-25,2025-10-25%0A45.5017,-73.5228,,EST,2025-10-26,2025-10-26%0A45.5017,-73.5228,,EST,2025-11-07,2025-11-07%0A45.5017,-73.5228,,EST,2025-11-08,2025-11-08%0A41.57,2.2611,,EST,2025-11-08,2025-11-08%0A41.57,2.2611,,EST,2025-11-09,2025-11-09%0A41.57,2.2611,,EST,2025-11-21,2025-11-22%0A41.57,2.2611,,EST,2025-11-22,2025-11-23%0A41.57,2.2611,,EST,2025-11-28,2025-11-28%0A47.2197,14.7647,,EST,2025-11-29,2025-11-29%0A47.2197,14.7647,,EST,2025-11-29,2025-11-29%0A47.2197,14.7647,,EST,2025-11-30,2025-11-30%0A47.2197,14.7647,,EST,2025-12-06,2025-12-06%0A47.2197,14.7647,,EST,2025-12-07,2025-12-07&start_date=2023-01-01&end_date=2025-12-30&hourly=temperature_2m,precipitation,cloud_cover_low,cloud_cover_high,cloud_cover_mid,cloud_cover,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,wind_direction_100m,wind_speed_100m).